import re

def iso9(text: str) -> str:
    """
    Transliterates Cyrillic characters to Latin according to ISO 9 standard.
    
    Args:
        text: Input string containing Cyrillic characters.
        
    Returns:
        Transliterated string, or None if input is empty or contains unsupported characters.
    """
    iso9_lowercase = {
        'а': 'a', 
        'ӓ': 'ä', 
        'ӓ̄': 'ạ̈', 
        'ӑ': 'ă', 
        'а̄': 'ā', 
        'ӕ': 'æ', 
        'а́': 'á', 
        'а̊': 'å',
        'б': 'b', 
        'в': 'v', 
        'г': 'g',
        'ґ': 'g̀', 
        'ѓ': 'ǵ', 
        'ғ': 'ġ', 
        'ҕ': 'ğ', 
        'һ': 'ḥ',
        'д': 'd', 
        'ђ': 'đ', 
        'е': 'e', 
        'ӗ': 'ĕ', 
        'ё': 'ë', 
        'є': 'ê', 
        'ж': 'ž', 
        'җ': 'ž̦',
        'ӝ': 'z̄', 
        'ӂ': 'z̆', 
        'з': 'z', 
        'ӟ': 'z̈', 
        'ӡ': 'ź', 
        'ѕ': 'ẑ', 
        'и': 'i', 
        'ӣ': 'ī',
        'и́': 'í', 
        'ӥ': 'î', 
        'й': 'j', 
        'і': 'ì', 
        'ї': 'ï', 
        'і̄': 'ǐ', 
        'ј': 'ǰ', 
        'ј̵': 'j́',
        'к': 'k', 
        'ќ': 'ḱ', 
        'ӄ': 'ḳ', 
        'ҝ': 'k̂', 
        'ҡ': 'ǩ', 
        'ҟ': 'k̄', 
        'қ': 'k̦', 
        'к̨': 'k̀',
        'ԛ': 'q', 
        'л': 'l', 
        'љ': 'l̂', 
        'ԡ': 'l̦', 
        'м': 'm', 
        'н': 'n', 
        'њ': 'n̂', 
        'ң': 'n̦',
        'ӊ': 'ṇ', 
        'ҥ': 'ṅ', 
        'ԋ': 'ǹ', 
        'ԣ': 'ń', 
        'ӈ': 'ň', 
        'н̄': 'n̄', 
        'о': 'o', 
        'ӧ': 'ö',
        'ө': 'ô', 
        'ӫ': 'ő', 
        'о̄̈': 'ọ̈', 
        'ҩ': 'ò', 
        'о́': 'ó', 
        'о̄': 'ō', 
        'œ': 'œ', 
        'п': 'p',
        'ҧ': 'ṕ', 
        'ԥ': 'p̀', 
        'р': 'r', 
        'с': 's', 
        'ҫ': 'ș', 
        'с̀': 's̀', 
        'т': 't', 
        'ћ': 'ć',
        'ԏ': 't̀', 
        'т̌': 'ť', 
        'ҭ': 'ț', 
        'у': 'u', 
        'ӱ': 'ü', 
        'ӯ': 'ū', 
        'ў': 'ŭ', 
        'ӳ': 'ű',
        'у́': 'ú', 
        'ӱ̄': 'ụ̈', 
        'ү': 'ù', 
        'ұ': 'u̇', 
        'ԝ': 'w', 
        'ф': 'f', 
        'х': 'h', 
        'ҳ': 'h̦',
        'ц': 'c', 
        'ҵ': 'c̄', 
        'џ': 'd̂', 
        'ч': 'č', 
        'ҷ': 'c̦', 
        'ӌ': 'c̣', 
        'ӵ': 'c̈', 
        'ҹ': 'ĉ',
        'ч̀': 'c̀', 
        'ҽ': 'c̆', 
        'ҿ': 'c̨̆', 
        'ш': 'š', 
        'щ': 'ŝ', 
        'ъ': 'ʺ', 
        'ы': 'y', 
        'ӹ': 'ÿ',
        'ы̄': 'ȳ', 
        'ь': 'ʹ', 
        'э': 'è', 
        'ә': 'a̋', 
        'ӛ': 'à', 
        'ю': 'û', 
        'ю̄': 'û̄', 
        'я': 'â',
        'ѣ': 'ě', 
        'ѫ': 'ǎ', 
        'ѳ': 'f̀', 
        'ѵ': 'ỳ', 
        'Ӏ': '‡', 
        'ʼ': 'ʼ', 
        'ˮ': 'ˮ'
    }

    if text is None or not isinstance(text, str) or not text.strip():
        return None

    result = []
    for char in text.lower():
        if char in iso9_lowercase:
            result.append(iso9_lowercase[char])
        elif char.isalpha():
            return None  # Contains an unsupported letter → terminate
        else:
            result.append(char)

    return ''.join(result)